feat(Home): renamed components name and refactored some codes.
onja-org/vamalaka-nivia pull request #5
Opened 2021-07-13 05:46 UTC by ravinalamada

Hi team,

This is role-selectionOnboardingOne from Nivia team. We did some refactors in this branch. Can you review it please? We'd like to get any comments in order to get it improved.

Refs: #41k8dk

Thanks in advance,

2021-07-13 05:59 UTC, andrzej-onja requested changes

2021-07-13 05:59 UTC, andrzej-onja commented on src/components/RoleSelectOption/RoleSelectOption.tsx
> +        <div className='polygon-bg-image'>
We are using styled components so no class names assignments.
Please extract div into separate styled one

2021-07-13 05:59 UTC, andrzej-onja commented on src/components/Home/Home.tsx
> +export const Home: React.FC<Props> = ({ footerLinks }) => {
Create a new folder Pages and put this component inside. Also rename it to HomePage

2021-07-14 06:44 UTC, andrzej-onja commented on src/App.tsx
> +import { Home } from './Pages/HomePage.story'
HomePage.story ?

2021-07-14 06:44 UTC, andrzej-onja commented on src/components/RoleSelectOption/RoleSelectOption.tsx
> +export const Option: React.FC<OptionProps> = ({
Rename to RoleSelectOption

2021-07-14 06:44 UTC, andrzej-onja commented on src/components/RoleSelectOption/RoleSelectOption.tsx
> +export const Option: React.FC<OptionProps> = ({
add onClick prop

2021-07-14 06:44 UTC, andrzej-onja commented on src/components/RoleSelectionOnboardingOne/RoleSelectionOnBoardingOne.tsx
> +export const RoleSelectOnboardOne = () => {
Rename to  just RoleSelectOnboard

2021-07-14 06:44 UTC, andrzej-onja commented on src/components/RoleSelectionOnboardingOne/RoleSelectionOnBoardingOneStyle.tsx
> +import styled from 'styled-components'
rename RoleSelectOnboardStyle

2021-07-16 07:59 UTC, andrzej-onja approved these changes

2021-07-16 07:59 UTC, andrzej-onja commented on src/components/RoleSelectionOnboard/RoleSelectionOnBoard.tsx
> +export const RoleSelectOnboard = () => {
useState,  [selectedRole,setSelectedRole] - called from RoleSelectOption wit selected role string

2021-07-16 08:00 UTC, vakodrazan approved these changes

2021-07-16 08:01 UTC, bakozetra approved these changes

2021-07-16 08:01 UTC, merged